### ISSUE TITLE
How to insert log field in Job arguments?

### ISSUE THREAD

**Issue by blacknon** [Graylog2/graylog2-alarmcallback-rundeck#3]
Can not pass the value of the variable in Rundeck from Graylog.
It runs the tcpdump to put a value to the field arguments, but it does not go flying packet.

How to use "Job arguments" or "Field arguments"?
I insert Field arguments into "message:${message.message}"

**Comment by joschi** [comment]
@blacknon You can simply provide the name of the message fields to include in the "Field arguments" setting:

https://github.com/Graylog2/graylog-plugin-rundeck#job-arguments

The contents will then be added as a job parameter named like the message field to the Rundeck invocation, e. g. if you add "message" to the "Field arguments" setting, this plugin will pass a job parameter named "message" with the contents of the "message" field to the Rundeck job invocation.
